import "./globals.css";

import type { Metadata } from "next";
import { Barlow, Barlow_Condensed, Bellefair } from "next/font/google";

import Header from "./_components/header";

const BellefairFont = Bellefair({
  subsets: ["latin"],
  weight: "400",
});

const BarlowFont = Barlow({
  subsets: ["latin"],
  weight: "400",
});

const BarlowCondensedFont = Barlow_Condensed({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BellefairFont.className} ${BarlowFont.className} ${BarlowCondensedFont.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
