import type { Metadata } from "next";
import { Bellefair, Barlow, Barlow_Condensed } from "next/font/google";
import "./globals.css";

const BellefairFont = Bellefair({
  subsets: ["latin"],
  weight: "400",
});

const BarlowFont = Barlow({
  subsets: ["latin"],
  weight: "400",
});

const BarlowCondensedFont = Barlow_Condensed({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BellefairFont.className} ${BarlowFont.className} ${BarlowCondensedFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
