import type { Metadata } from "next";
import "./globals.css";
import { Rubik } from "next/font/google";

const RubikFont = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Time tracking dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RubikFont.className} bg-neutral-very-dark-blue`}>
        {children}
      </body>
    </html>
  );
}
